version: '3'

services:
  imgweb:
    environment:
      - DB_NAME=fileapp_db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=imgdb
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=mysite.settings.prod
    build: .
    volumes:
      - .:/code
    ports:
      - "3344:3344"
    restart: "always"
    depends_on:
      - imgdb
  imgdb:
    image: postgres
    environment:
      - POSTGRES_DB=fileapp_db
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    restart: "always"